// mock_service.dart
import 'package:mockito/mockito.dart';
import 'package:young_arts/common/image_resources.dart';
import 'package:young_arts/features/artwork/domain/entities/artwork.dart';
import 'package:young_arts/features/profile/data/models/user_profile_model.dart';

class MockService extends Mock {
  Future<List<UserProfileModel>> fetchUsers() async {
    return [
      const UserProfileModel(
        id: 1,
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        role: 'Student',
        school: 'School',
        yearGroup: 'Year 1',
        artworks: [
          Artwork(
            id: 1,
            title: 'Artwork 1',
            artist: 'John Doe',
            imageUrl: ImageResources.BIRD,
            description: 'Description 1',
          ),
        ],
      ),
      const UserProfileModel(
        id: 2,
        firstName: 'Jane',
        lastName: 'Doe',
        email: 'jane.doe@example.com',
        role: 'Student',
        school: 'School 2',
        yearGroup: 'Year 2',
        artworks: [
          Artwork(
            id: 2,
            title: 'Artwork 2',
            artist: 'Jane Doe',
            imageUrl: ImageResources.BLOCKED_COLOURS,
            description: 'Description 2',
          ),
        ],
      ),
      const UserProfileModel(
        id: 3,
        firstName: 'Alice',
        lastName: 'Smith',
        email: 'alice.smith@example.com',
        role: 'Student',
        school: 'School 3',
        yearGroup: 'Year 3',
        artworks: [
          Artwork(
            id: 3,
            title: 'Artwork 3',
            artist: 'Alice Smith',
            imageUrl: ImageResources.BLUE_STREAKS,
            description: 'Description 3',
          ),
        ],
      ),
      const UserProfileModel(
        id: 4,
        firstName: 'Bob',
        lastName: 'Johnson',
        email: 'bob.johnson@example.com',
        role: 'Student',
        school: 'School 4',
        yearGroup: 'Year 4',
        artworks: [
          Artwork(
            id: 4,
            title: 'Artwork 4',
            artist: 'Bob Johnson',
            imageUrl: ImageResources.CHURCH_ARCH,
            description: 'Description 4',
          ),
        ],
      ),
      const UserProfileModel(
        id: 5,
        firstName: 'Charlie',
        lastName: 'Brown',
        email: 'charlie.brown@example.com',
        role: 'Student',
        school: 'School 5',
        yearGroup: 'Year 5',
        artworks: [
          Artwork(
            id: 5,
            title: 'Artwork 5',
            artist: 'Charlie Brown',
            imageUrl: ImageResources.COLORFUL_FLOWERS,
            description: 'Description 5',
          ),
          Artwork(
            id: 22,
            title: 'Artwork 22',
            artist: 'Charlie Brown',
            imageUrl: ImageResources.SAILING,
            description: 'Description 5',
          ),
          Artwork(
            id: 23,
            title: 'Artwork 5',
            artist: 'Charlie Brown',
            imageUrl: ImageResources.SOPHISTICATED_BIRDS,
            description: 'Description 5',
          ),
        ],
      ),
      const UserProfileModel(
        id: 6,
        firstName: 'David',
        lastName: 'Williams',
        email: 'david.williams@example.com',
        role: 'Student',
        school: 'School 6',
        yearGroup: 'Year 6',
        artworks: [
          Artwork(
            id: 6,
            title: 'Artwork 6',
            artist: 'David Williams',
            imageUrl: ImageResources.COLOR_STREAKS,
            description: 'Description 6',
          ),
        ],
      ),
      const UserProfileModel(
        id: 7,
        firstName: 'Eva',
        lastName: 'Jones',
        email: 'eva.jones@example.com',
        role: 'Student',
        school: 'School 7',
        yearGroup: 'Year 7',
        artworks: [
          Artwork(
            id: 7,
            title: 'Artwork 7',
            artist: 'Eva Jones',
            imageUrl: ImageResources.COTTAGE,
            description: 'Description 7',
          ),
          Artwork(
            id: 24,
            title: 'Artwork 24',
            artist: 'Eva Jones',
            imageUrl: ImageResources.SOPHISTICATED_BIRDS,
            description: 'Description 7',
          ),
        ],
      ),
      const UserProfileModel(
        id: 8,
        firstName: 'Frank',
        lastName: 'Taylor',
        email: 'frank.taylor@example.com',
        role: 'Student',
        school: 'School 8',
        yearGroup: 'Year 8',
        artworks: [
          Artwork(
            id: 8,
            title: 'Artwork 8',
            artist: 'Frank Taylor',
            imageUrl: ImageResources.CROWDED_HEAVEN,
            description: 'Description 8',
          ),
        ],
      ),
      const UserProfileModel(
        id: 9,
        firstName: 'Grace',
        lastName: 'Anderson',
        email: 'grace.anderson@example.com',
        role: 'Student',
        school: 'School 9',
        yearGroup: 'Year 9',
        artworks: [
          Artwork(
            id: 9,
            title: 'Artwork 9',
            artist: 'Grace Anderson',
            imageUrl: ImageResources.DARK_FLOWERS,
            description: 'Description 9',
          ),
        ],
      ),
      const UserProfileModel(
        id: 10,
        firstName: 'Harry',
        lastName: 'Thomas',
        email: 'harry.thomas@example.com',
        role: 'Student',
        school: 'School 10',
        yearGroup: 'Year 10',
        artworks: [
          Artwork(
            id: 10,
            title: 'Artwork 10',
            artist: 'Harry Thomas',
            imageUrl: ImageResources.FANTASY_MOUNTAINS,
            description: 'Description 10',
          ),
          Artwork(
            id: 21,
            title: 'Artwork 21',
            artist: 'Harry Thomas',
            imageUrl: ImageResources.ROAD_TO_THE_MOUNTAINS,
            description: 'Description 10',
          ),
        ],
      ),
      const UserProfileModel(
        id: 11,
        firstName: 'Ivy',
        lastName: 'Jackson',
        email: 'ivy.jackson@example.com',
        role: 'Student',
        school: 'School 11',
        yearGroup: 'Year 11',
        artworks: [
          Artwork(
            id: 11,
            title: 'Artwork 11',
            artist: 'Ivy Jackson',
            imageUrl: ImageResources.GIRL,
            description: 'Description 11',
          ),
          Artwork(
            id: 20,
            title: 'Artwork 20',
            artist: 'Ivy Jackson',
            imageUrl: ImageResources.SAILING,
            description: 'Description 16',
          ),
        ],
      ),
      const UserProfileModel(
        id: 12,
        firstName: 'Jack',
        lastName: 'White',
        email: 'jack.white@example.com',
        role: 'Student',
        school: 'School 12',
        yearGroup: 'Year 12',
        artworks: [
          Artwork(
            id: 12,
            title: 'Artwork 12',
            artist: 'Jack White',
            imageUrl: ImageResources.HAY_BAILS,
            description: 'Description 12',
          ),
        ],
      ),
      const UserProfileModel(
        id: 13,
        firstName: 'Kate',
        lastName: 'Harris',
        email: 'kate.harris@example.com',
        role: 'Student',
        school: 'School 13',
        yearGroup: 'Year 13',
        artworks: [
          Artwork(
            id: 13,
            title: 'Artwork 13',
            artist: 'Kate Harris',
            imageUrl: ImageResources.JAPANESE_MOUNTAIN_SIDE,
            description: 'Description 13',
          ),
        ],
      ),
      const UserProfileModel(
        id: 14,
        firstName: 'Luke',
        lastName: 'Martin',
        email: 'luke.martin@example.com',
        role: 'Student',
        school: 'School 14',
        yearGroup: 'Year 14',
        artworks: [
          Artwork(
            id: 14,
            title: 'Artwork 14',
            artist: 'Luke Martin',
            imageUrl: ImageResources.MOUNTAIN_LAKE,
            description: 'Description 14',
          ),
        ],
      ),
      const UserProfileModel(
        id: 15,
        firstName: 'Mia',
        lastName: 'Thompson',
        email: 'mia.thompson@example.com',
        role: 'Student',
        school: 'School 15',
        yearGroup: 'Year 15',
        artworks: [
          Artwork(
            id: 15,
            title: 'Artwork 15',
            artist: 'Mia Thompson',
            imageUrl: ImageResources.MOUNTAIN_LAKE,
            description: 'Description 15',
          ),
        ],
      ),
      const UserProfileModel(
        id: 16,
        firstName: 'Nick',
        lastName: 'Garcia',
        email: 'nick.garcia@example.com',
        role: 'Student',
        school: 'School 16',
        yearGroup: 'Year 16',
        artworks: [
          Artwork(
            id: 16,
            title: 'Artwork 16',
            artist: 'Nick Garcia',
            imageUrl: ImageResources.PINK_FLOWERS,
            description: 'Description 16',
          ),
          Artwork(
            id: 17,
            title: 'Artwork 17',
            artist: 'Nick Garcia',
            imageUrl: ImageResources.RED_FLOWERS,
            description: 'Description 16',
          ),
        ],
      ),
      const UserProfileModel(
        id: 17,
        firstName: 'Olivia',
        lastName: 'Martinez',
        email: 'olivia.martinez@example.com',
        role: 'Student',
        school: 'School 17',
        yearGroup: 'Year 17',
        artworks: [
          Artwork(
            id: 18,
            title: 'Artwork 17',
            artist: 'Olivia Martinez',
            imageUrl: ImageResources.RIVER,
            description: 'Description 17',
          ),
          Artwork(
            id: 19,
            title: 'Artwork 19',
            artist: 'Olivia Martinez',
            imageUrl: ImageResources.RIVER_CATTLE,
            description: 'Description 16',
          ),
        ],
      )
    ];
  }
}
